#@TYPE: Machine
#@NAME: GTA04A5
#@SOC: OMAP3
#@DESCRIPTION: Machine configuration for GTA04A4
#@MAINTAINER: Josua Mayer <josua.mayer@jm0.eu>

# Tune for Cortex-A8, with Thumb, VFP and Neon
DEFAULTTUNE ?= "cortexa8thf-neon"
require conf/machine/include/arm/armv7a/tune-cortexa8.inc

# define machine features per yocto reference manual:
# https://docs.yoctoproject.org/ref-manual/features.html
# TODO: SOme of them seem unused, reduce to useful minimum
MACHINE_FEATURES += "alsa bluetooth ext2 phone qemu-usermode rtc screen serial touchscreen usbgadget usbhost vfat vga wifi"

# Define image types:
# - tar.bz2: rootfs
# - TODO: wic: for bootable microSD with bootloader, boot- and rootfs partitions
# - TODO: ubifs / onenand
IMAGE_FSTYPES += "tar.bz2"

# require downstream u-boot
PREFERRED_PROVIDER_virtual/bootloader = "u-boot-gta04"
UBOOT_ARCH ?= "arm"
UBOOT_MACHINE ?= "letux_gta04_defconfig"
UBOOT_ENTRYPOINT = "0x80008000"
UBOOT_LOADADDRESS = "0x80008000"
SPL_BINARY = "MLO"
UBOOT_SUFFIX = "img"
