#@TYPE: Machine
#@NAME: GTA04
#@SOC: OMAP3
#@DESCRIPTION: Machine configuration for GTA04
#@MAINTAINER: Josua Mayer <josua.mayer@jm0.eu>

# Tune for Cortex-A8, with Thumb, VFP and Neon
DEFAULTTUNE ?= "cortexa8thf-neon"
require conf/machine/include/arm/armv7a/tune-cortexa8.inc

# define machine features per yocto reference manual:
# https://docs.yoctoproject.org/ref-manual/features.html
# TODO: SOme of them seem unused, reduce to useful minimum
MACHINE_FEATURES += "alsa bluetooth ext2 phone qemu-usermode rtc screen serial touchscreen usbgadget usbhost vfat vga wifi"

# require downstream u-boot
PREFERRED_PROVIDER_virtual/bootloader = "u-boot-gta04"
UBOOT_ARCH ?= "arm"
UBOOT_MACHINE ?= "letux_gta04_defconfig"
UBOOT_ENTRYPOINT = "0x80008000"
UBOOT_LOADADDRESS = "0x80008000"
SPL_BINARY = "MLO"
UBOOT_SUFFIX = "img"

# use downstream kernel
PREFERRED_PROVIDER_virtual/kernel = "linux-gta04"
KERNEL_IMAGETYPE = "uImage"
KEEPUIMAGE = "no"
KERNEL_DEVICETREE = " \
    ti/omap/omap3-gta04a2.dtb \
    ti/omap/omap3-gta04a3.dtb \
    ti/omap/omap3-gta04a4.dtb \
    ti/omap/omap3-gta04a5.dtb \
"

# Define bootable sdcard files
WKS_FILE = "gta04-sdcard.wks"
# copy u-boot and boot-menu to boot-partition
# TODO: MLO.flash, u-boot.img.flash
IMAGE_BOOT_FILES ?= " \
    ${SPL_BINARY} \
    u-boot.${UBOOT_SUFFIX} \
    boot.scr \
    menu.rgb16z \
    splash.rgb16z \
"
do_image_wic[depends] += "virtual/bootloader:do_deploy"

# Define image types:
# - tar.bz2: rootfs
# - wic: for bootable microSD with bootloader, boot- and rootfs partitions
# - TODO: ubifs / onenand
IMAGE_FSTYPES += "tar.bz2 wic.xz wic.bmap"

# include packages essential for boot
MACHINE_ESSENTIAL_EXTRA_RDEPENDS = " \
    kernel \
    kernel-devicetree \
"

# spawn getty on serial console
SERIAL_CONSOLES = "115200;ttyO2"
